[package]
name = "strato"
version = "0.1.0"
authors = ["Leon Tan <leon.arian.tan@gmail.com>"]
edition = "2018"

[dependencies]
fuse = "0.3"
parking_lot = "0.7"
libc = "0.2.47"


[dev-dependencies]
env_logger = "0.6.0"