[package]
name = "fuse-strato"
version = "0.1.0"
authors = ["Leon Tan <leon.arian.tan@gmail.com>"]
edition = "2018"

[dependencies]
fuse-sys = {path = "../fuse-sys", version="0.4.0-alpha"}
futures = "0.1"
tokio = "0.1"
bytes = "0.4"

[dev-dependencies]
env_logger = "0.6"
hexdump = "0.1"
